### ISSUE TITLE
데이터 공개 질문

### ISSUE THREAD

**Issue by Blackstarez** [KUNLP/KU_Sentiment-Analysis#4]
현재 사용한 데이터를 공개하지 않으셨는데, 

혹시 데이터 공개할 예정인가요?

**Comment by Blackstarez** [comment]
You did not published the data you currently used.

Are you planning to make your data public?

**Comment by Mongjin** [comment]
No, we provided NSMC data, please see our README and click the NSMC dataset links and then you can download it!
